version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=globetrek
      - POSTGRES_USER=globetrek
      - POSTGRES_PASSWORD=globetrek
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-l_-p9gehx0n=^73ow2d==is-%hnx755!8$q@+5bwjb2h8#hgjp
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=globetrek
      - SQL_USER=globetrek
      - SQL_PASSWORD=globetrek
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
