# Generated by Django 5.2.6 on 2025-10-13 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tenant_privatenote_userprofile_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('employer', 'Empleador'), ('employee', 'Empleado')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('first_image', models.ImageField(blank=True, null=True, upload_to='bookings/')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('hotel_name', models.CharField(max_length=255)),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='bookings/')),
                ('room_type', models.CharField(choices=[('single', 'Individual'), ('double', 'Doble'), ('suite', 'Suite')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Teléfono debe ser numérico (7-15 dígitos).', regex='^\\+?\\d{7,15}$')])),
                ('room_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_count', models.PositiveIntegerField()),
                ('guests_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.tenant')),
            ],
        ),
    ]
