# Generated by Django 5.2.6 on 2025-10-13 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_role_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(db_index=True, default=1, max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Código debe tener 5 letras mayúsculas seguidas de 1 o 2 dígitos.', regex='^[A-Z]{5}\\d{1,2}$')]),
            preserve_default=False,
        ),
    ]
